id = "haml"
name = "Haml"
version = "0.0.1"
schema_version = 1
description = "Haml template support."
repository = "https://github.com/croaky/zed-haml"
authors = ["croaky"]

[grammars.haml]
repository = "https://github.com/croaky/tree-sitter-haml"
rev = "b7f762fb67aa86c6af9ed1a6e702bdac126f8090"
